# Generated by Django 4.2.9 on 2024-03-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventScheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendingCount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
